### ISSUE TITLE
m3u playlist not working

### ISSUE THREAD

**Issue by borisneubert** [clark15b/xupnpd2#10]
Compiled current github version of xupnpd2 and ran it. VLC on remote host can see xupnpd2. VLC plays included example.m3u playlist (OTT-HLS). So far, so good.

Now to the issue. I copied current playlist from here:

https://sites.google.com/site/dailym3uiptv/dl/de-160619-dailym3uiptv.com-1.m3u?attredirects=0&d=1

to media folder. VLC on remote host can also see that playlist but does not play any stream. VLC gives the error: "VLC cannot open media address http://XUNPNPD2-HOST:4044/stream/STREAMNUMBER.ts"

Running any included stream directly from VLC works. Just try 

http://clientbox.tv:80/live/Zdocy2bPM9/NB3xkLiy6J/3557.m3u8

How can this issue be solved?

**Comment by clark15b** [comment]
Hi, now clientbox.tv return 404 for all playlist entrys (vlc, chrome ..).
Is it works for you?

**Comment by borisneubert** [comment]
Thank you so much for replying!

Looks like the server has gone out of service since then. Please find attached another playlist which does not work either with xupnpnd2. It works if opened with VLC.

[de-020719-dailym3uiptv.com-1.m3u.gz](https://github.com/clark15b/xupnpd2/files/3351751/de-020719-dailym3uiptv.com-1.m3u.gz)

DE: DAS ERSTE and DE: ZDF are free to view.

**Comment by clark15b** [comment]
Try this: https://github.com/clark15b/xupnpd-live

**Comment by borisneubert** [comment]
Great, it works. Thank you.

Note: on debian 10.0, one needs to install lua5.1 and liblua5.1-dev (5.3 hasn't lua_open anymore) and change the compiler flags as follows:

`g++ -DWITH_SSL -Imbedtls/include -Lmbedtls/library -I. -I/usr/include/lua5.1 -o xupnpd-live main.cpp ssdp.cpp server.cpp worker.cpp producer.cpp m3u8.cpp curl.cpp hls.cpp config.cpp common.cpp soap.cpp log.cpp json.cpp xml.cpp luaaux.cpp -lmbedtls -lmbedx509 -lmbedcrypto -llua5.1`
