### ISSUE TITLE
hls-stream not working

### ISSUE THREAD

**Issue by thomasschmiedl** [clark15b/xupnpd2#3]
The hls-stream in https://www.wetter.com/hd-live-webcams/tschechien/prague/556ea720e8c1b/ (link to m3u8-playlist in html-tag 'data-video-url-hls') is not working in the current xupnpd2 open-source version. The stream works in xupnpd-2.0-16.195.1914-beta closed-source version. The m3u8-url is also downloadable via 'http', not only 'https'.

**Comment by clark15b** [comment]
fixed
