### ISSUE TITLE
Field SourceIP in RTP URL not supported for MagentaTV

### ISSUE THREAD

**Issue by delfinsk** [clark15b/xupnpd2#8]
The RTP url for Deutsche Telekom MagentaTV has the format
rtp://87.141.215.251@232.0.20.35:10000
where the part before the @ is SourceIP and the part after the @ is MulticastIP identifying the Multicast group. A short look at the documentation and into the source code showed that this format does not seem to be supported and I did not get it working either.

Best regards
delfinsk

**Comment by delfinsk** [comment]
This  patch fixes the issue for me:

[patch.txt](https://github.com/clark15b/xupnpd2/files/4113593/patch.txt)

Best regards
delfinsk

**Comment by clark15b** [comment]
Tnx!
